create table People (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chatId BIGINT NOT NULL,
    name VARCHAR(100),
    date_of_birth DATE NOT NULL,
    timezone VARCHAR(32) DEFAULT 'UTC',
    is_active BOOLEAN DEFAULT TRUE
);